version: '3.8'

services:
  web:
    build: .
    container_name: laptopxplorer_web
    command: gunicorn --bind 0.0.0.0:1480 --workers 3 config.wsgi:application
    volumes:
      - ./src:/app/src
      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles
    ports:
      - "1480:1480"
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-change-this-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,laptopxplorer.ayubsoft-inc.systems
      - CSRF_TRUSTED_ORIGINS=http://localhost:1480,https://laptopxplorer.ayubsoft-inc.systems
      - DATABASE_URL=sqlite:///db.sqlite3
    restart: unless-stopped

